### PR TITLE
feat: move to lucia auth and drizzle orm

### PR DESCRIPTION
**Pull request by SrIzan10**
attempt to make tbh the most easy to selfhost app ever (potentially)
also more stable
also more beautiful

### CODE REVIEW

**Comment by SrIzan10** [comment]
we do not care cloudflare

**Comment by willysuna** [comment]
callate alaverga cloudflar e,

**Comment by SrIzan10** [comment]
top diez prs más serios

**Comment by SrIzan10** [comment]
alright im ready to pair

**Pull request merged**
